### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## 2.
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)

In [4]:
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

## 3.
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [9]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 6)

In [10]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 4.
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

### Ответ - нельзя!


In [15]:
a5.shape

(12, 1)

## 5.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [16]:
a = np.random.randn(3, 4)
a

array([[ 0.41711918,  0.0925709 , -0.14956863,  0.25906723],
       [ 1.06234014, -0.92407324,  0.0613568 , -2.48529185],
       [-0.76905729, -0.02226841, -2.10259726, -0.45696466]])

In [17]:
a.size

12

In [18]:
a_flat = a.flatten()
a_flat

array([ 0.41711918,  0.0925709 , -0.14956863,  0.25906723,  1.06234014,
       -0.92407324,  0.0613568 , -2.48529185, -0.76905729, -0.02226841,
       -2.10259726, -0.45696466])

In [19]:
a_flat.size

12

## 6.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, step=-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])