### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## 2.
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)

In [4]:
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

## 3.
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [9]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 6)

In [10]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 4.
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

### Ответ - нельзя!


In [15]:
a5.shape

(12, 1)

## 5.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [16]:
a = np.random.randn(3, 4)
a

array([[-0.71974073,  1.80948032,  0.08825996, -0.89529605],
       [-1.393235  , -0.95050932, -1.28456093, -0.50456764],
       [ 0.41341904, -0.32547884,  0.2450952 ,  1.23942223]])

In [17]:
a.size

12

In [18]:
a_flat = a.flatten()
a_flat

array([-0.71974073,  1.80948032,  0.08825996, -0.89529605, -1.393235  ,
       -0.95050932, -1.28456093, -0.50456764,  0.41341904, -0.32547884,
        0.2450952 ,  1.23942223])

In [19]:
a_flat.size

12

## 6.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, step=-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## 7.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [21]:
b = np.arange(20, 1, step=-2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [22]:
# Разница: a - одномерный, b - двухмерный
a.shape == b.shape

False

## 8.
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
v.size

10

## 9.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 


In [27]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
# Получить матрицу At путем транспонирования матрицы A.
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [30]:
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
# B.shape = numOf_cols(At) x numOf_rows(A)
B.shape

(4, 4)

In [32]:
# Обратную матрицу вычислить не получится
B_det = np.linalg.det(B)
B_det

0.0