### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## 2.
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)

In [4]:
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

## 3.
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [9]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 6)

In [10]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 4.
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

### Ответ - нельзя!


In [15]:
a5.shape

(12, 1)

## 5.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [16]:
a = np.random.randn(3, 4)
a

array([[-0.48247267, -0.59613999,  0.24996206, -0.40607301],
       [-1.26280014,  0.53080285, -0.60718984,  0.62363252],
       [-0.15968747,  0.11702464,  0.56902   , -1.44672543]])

In [17]:
a.size

12

In [18]:
a_flat = a.flatten()
a_flat

array([-0.48247267, -0.59613999,  0.24996206, -0.40607301, -1.26280014,
        0.53080285, -0.60718984,  0.62363252, -0.15968747,  0.11702464,
        0.56902   , -1.44672543])

In [19]:
a_flat.size

12

## 6.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, step=-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## 7.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [21]:
b = np.arange(20, 1, step=-2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [22]:
# Разница: a - одномерный, b - двухмерный
a.shape == b.shape

False

## 8.
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
v.size

10

## 9.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 


In [27]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
# Получить матрицу At путем транспонирования матрицы A.
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [30]:
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
# B.shape = numOf_cols(At) x numOf_rows(A)
B.shape

(4, 4)

In [32]:
# Обратную матрицу вычислить не получится
B_det = np.linalg.det(B)
B_det

0.0

## 10.
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [33]:
a = np.random.seed(42)

## 11.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [34]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

## 12.

In [35]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C.
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [36]:
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
D = B + C * 10
D


array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [37]:
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
np.linalg.det(D)

-28511999.999999944

In [38]:
np.linalg.matrix_rank(D)

4

In [39]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

## 13.

In [40]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
# Убедитесь, что в матрице D_inv остались только нули и единицы.
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [41]:
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, 
# а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [42]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [43]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [44]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])